[package]
name = "hardware-agnostic-utils"
version = "0.1.0"
authors = ["Stefan Dangl <tzuzuzj@gmx.at>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[dependencies]
smart-leds = "0.4"
thiserror = "2.0"

[dev-dependencies]
test-case = "3.3"