name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_fmt:
    name: Check Rust Format (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true
      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    name: Lint with Clippy
    runs-on: ubuntu-latest
    needs: check_fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: clippy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: esp32s3
          ldproxy: true
      - name: Run Tests
        working-directory: ./hardware-agnostic-utils  
        run: cargo test --target x86_64-unknown-linux-gnu